### PR TITLE
update mcp-common version

### PR DESCRIPTION
**Pull request by tiridor34**
- updated references to Clock
- updated unit tests
- removed unused TimePoint reference in unit test
- updated travis config
  - 5.6 & 7.0 is no longer supported under mcp-common 2.*
- updated composer config to require php 7.1 or newer

### CODE REVIEW

**Comment by skluck** [comment]
Looks good, sorry for the delay. I'll merge and tag before monday, and probably update to circle ci while I'm at it.

Do you think this is a major bump? I think we can get away with just a minor version bump since no api or functionality is changed - just dependency requirements.

**Comment by tiridor34** [comment]
I do think it is a major bump only because the previous versions permitted PHP 5.6 & 7.0. With the mcp-common update requiring >=php 7.1, this is no longer the case. So anyone still using older PHP versions won't be able to update to this version. Thoughts?

**Comment by skluck** [comment]
Theoretically the composer requirements would just always prevent it from installing on those versions. If any bugs presented themselves we'd still always be able to do a 3.0.1, 3.0.2, etc which those apps could still receive.

If you're on 7.1, 7.3, etc and you updated there would be nothing to change, since the use of mcp-common time is only internal and not a part of the external api so thats why I would favor less than major.

So I would prefer `3.1.0` instead of `4.0.0` but I'm open to your further ideas.

**Comment by tiridor34** [comment]
That's a great point. A minor version bump does then make the most sense.

**Pull request merged**
